### ISSUE TITLE
Memory scaleability admin view

### ISSUE THREAD

**Issue by CalleP** [valdisiljuconoks/localization-provider-opti#175]
Hi!
We’ve been using DbLocalizationProvider (version 5.8.2.0, we’re not on EPI12 yet) successfully for a few years now. Smooth sailing! 

However, last sprint we noticed that the Admin page has exceeded the memory limit of chrome and other browsers. (69 columns, more than 1k rows, more than 100k cells.)
![image](https://user-images.githubusercontent.com/6671809/196428739-97d30731-a729-45de-9b43-5fd6918b4680.png)

![image2](https://user-images.githubusercontent.com/6671809/196428859-0a9331bb-6fab-489d-8b58-5c98efa6dc94.png)

This is likely due to all the elements being pre-loaded. Some sort of pagination or dynamic loading I’d imagine would scale better! 😊
But we can circumvent this on our end by using browsers with a higher memory limit or running chrome with different parameters.

I thought it’d be nice to be aware of this issue and it might no longer be an issue in your later versions, but from what I could tell it’s still there. Is this something you intend to change?

**Comment by valdisiljuconoks** [comment]
Hi,

Yeah. Admin UI is crap :) I was considering to add paging, dynamic loading, or both :) But you know - time is the limit always..

**Comment by valdisiljuconoks** [comment]
should be addressed by https://github.com/valdisiljuconoks/localization-provider-opti/issues/194

**Comment by valdisiljuconoks** [comment]
And https://github.com/valdisiljuconoks/localization-provider-opti/pull/195 for v6.x
