### ISSUE TITLE
Exception thrown when deleting a key through the Import option

### ISSUE THREAD

**Issue by CarlosAlbuquerqueWeir** [valdisiljuconoks/localization-provider-opti#196]
Every time I try to delete a key by importing a file the import endpoint fails with an exception. In our current system we have 196 keys and I used the following json to create a new one:

```javascript
[
  {
    "id": 197,
    "resourceKey": "Test.NewKey",
    "modificationDate": "2023-02-10T10:50:17.9666667Z",
    "author": "type-scanner",
    "fromCode": true,
    "isModified": false,
    "isHidden": false,
    "translations": [
      {
        "id": 394,
        "resourceId": 196,
        "language": "es-mx",
        "value": "Nueva llave",
        "modificationDate": "2023-02-10T10:50:17.9766667Z"
      }
    ]
  }
]
```

This works fine and creates the key and the label in the correct places. However, uploading a file without this key (pls change the extension to JSON as it was not supported by Github):
[localization-resources-20230406_ESMX.txt](https://github.com/valdisiljuconoks/localization-provider-epi/files/11450714/localization-resources-20230406_ESMX.txt)

Shows me the correct prompt
![image](https://github.com/valdisiljuconoks/localization-provider-epi/assets/124363599/79d347b0-dd59-4428-a677-edacf67ef661)

But clicking import results in a 500 error:
![image](https://github.com/valdisiljuconoks/localization-provider-epi/assets/124363599/e3b77abb-ba50-4e09-b52c-61c8dbd2dac0)

This is the request payload:
```javascript
[
   {
      "changeType": 3,
      "selected": true,
      "importingResource": {
         "id": 0,
         "resourceKey": "Test.NewKey",
         "modificationDate": "0001-01-01T00:00:00",
         "author": null,
         "fromCode": false,
         "isModified": null,
         "isHidden": null,
         "notes": null,
         "translations": []
      },
      "existingResource": {
         "id": 208,
         "resourceKey": "Test.NewKey",
         "modificationDate": "2023-05-11T09:43:02.87",
         "author": "import",
         "fromCode": true,
         "isModified": true,
         "isHidden": false,
         "notes": null,
         "translations": [
            {
               "id": 1242,
               "resourceId": 208,
               "language": "",
               "value": "Nueva llave",
               "modificationDate": "2023-05-11T09:43:02.86"
            },
            {
               "id": 1243,
               "resourceId": 208,
               "language": "es-MX",
               "value": "Nueva llave",
               "modificationDate": "2023-05-11T09:43:02.87"
            }
         ]
      },
      "changedLanguages": []
   }
]
```

The response contains the following stack trace:
> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
>    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>    at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
>    at DbLocalizationProvider.AdminUI.AspNetCore.ServiceController.ImportFile(List`1 changes)
>    at lambda_method6195(Closure , Object , Object[] )
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
>    at Weir.Global.CMS.Web.Infrastructure.AccessDeniedAuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in C:\Projects\weir\DXP-CMS\src\Weir.Global.CMS.Web\Infrastructure\AccessDeniedAuthorizationMiddlewareResultHandler.cs:line 25
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
>    at React.AspNet.BabelFileMiddleware.Invoke(HttpContext context)
>    at Weir.Global.CMS.Web.Infrastructure.ImageProcessor.Invoke(HttpContext httpContext, Boolean retry) in C:\Projects\weir\DXP-CMS\src\Weir.Global.CMS.Web\Infrastructure\ImageProcessor.cs:line 37
>    at Geta.NotFoundHandler.Infrastructure.Initialization.NotFoundHandlerMiddleware.InvokeAsync(HttpContext context, RequestHandler requestHandler)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

I did a bit of investigation and it seems the issue is on [line 115 of the ServiceController](https://github.com/valdisiljuconoks/localization-provider-core/blob/master/src/DbLocalizationProvider.AdminUI.AspNetCore/ServiceController.cs#L115). My bet is on the Json model that is being used to parse the request, but I will leave the rest to you now.

Expected behaviour:
The whole label key gets deleted from the database and does not show up on the Localization table

**Comment by valdisiljuconoks** [comment]
Hi,

Sorry for super late reply here. It's been a bit hetic lately. But I'm picking up this one..

Seems like issue is from the fact that resource has been imported with `"fromCode": false` attribute which prevents it from deleting it.

I'll see around - maybe these rules should be ignored when importing resources via files...
