### ISSUE TITLE
Error in AdminUI (not shown -> "Mixed-Content"-Error

### ISSUE THREAD

**Issue by fjeller** [valdisiljuconoks/localization-provider-opti#197]
Optimitely 12.20, Azure/Kubernetes, hosted in docker container.

The admin-UI of the localization provider is not shown.

The reason seems to be the the iFrame loads `/localization-admin` using http instead of https. I don't know why, seems to be a common problem. But it leads to the browser blocking that call and not showing the admin ui.

One fix seems to be be to add `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` to the calling page.  I would be grateful if you could do that, I'd be happy to get back to you and tell you if it worked.

**Comment by andrerim** [comment]
I'm are experiencing the same issue. Mabye another fix could be to add an option for specifiny absolute path of the `<iframe />` src when registering the service?

**Comment by valdisiljuconoks** [comment]
Hei,

Sorry for a delayed answer. It is interesting that `iframe` is trying to load content mixing up protocols. `iframe` src is a relative path usually set in `UiConfigurationContext.RootUrl` property (https://github.com/valdisiljuconoks/localization-provider-core/blob/master/src/DbLocalizationProvider.AdminUI.AspNetCore/UiConfigurationContext.cs#L81) which in theory shouldn't mix protocols but just follow the one original page was loaded in.

I'll take a look at header parameters to upgrade insecure requests.
