### ISSUE TITLE
Cache invalidation going nuts after upgrade to 8.x

### ISSUE THREAD

**Issue by toregjerdrum** [valdisiljuconoks/localization-provider-opti#220]
We released our Optimizely site on .NET 8 on 15.May. We upgraded all nugets as well, so we are running Optimizely on version 12.29.0 and DbLocalizationProvider on version 8.0.3. After the release, it looks like cache invalidation sends a lot of cache invalidation messages all the time. 

We are running the site in Azure and have 4 instances of the app service. If we peek the messages on the topic, the messages that are there is from dblocalizationprovidercache. See the attached image to se the increased amount of messages on the Azure Service Bus.
![image](https://github.com/valdisiljuconoks/localization-provider-opti/assets/1195937/bf4acfc5-a2ae-4784-a3cf-58149af3b130)

**Comment by toregjerdrum** [comment]
Not many changes done in the EPiServerCacheManager, but does [this](https://github.com/valdisiljuconoks/localization-provider-opti/commit/21dd3882fe17eac8d3415a28c92ea049b8add920) change make any sense?

**Comment by toregjerdrum** [comment]
A little update: We added our own EPiServerCacheManager where we removed the CacheManager.Remove(key) in the Insert metod. Now it looks good again.
https://github.com/valdisiljuconoks/localization-provider-opti/blob/1173b6b80b2172c37324db15788eb4972280be99/src/DbLocalizationProvider.EPiServer/EPiServerCacheManager.cs#L13

**Comment by valdisiljuconoks** [comment]
stupid cache :)

**Comment by valdisiljuconoks** [comment]
should be normalized in v8.1.0

**Comment by evest** [comment]
New packages are in the Opti Nuget feed now.
