### ISSUE TITLE
When they are duplicate entries then it is not possible to edit translation entry

### ISSUE THREAD

**Issue by dariusz-wozniak** [valdisiljuconoks/localization-provider-opti#223]
**When they are duplicate entries then it is not possible to edit translation entry**

It seems that duplicate ResourceKeys are allowed to be created. When I run the following query:

```
SELECT ResourceKey, count(1) count
  FROM [dbo].[LocalizationResources]
  group by ResourceKey
  having count(1) > 1
```

Then I can see 11 ResourceKeys with the following counts:

- 6525
- 2
- 4
- 1307
- 2
- 97067
- 4830
- 7801
- 2
- 17
- 18101

I had this problem locally for a while, but now it appears in the Dxp environment.

The version I'm using:

* DbLocalizationProvider.EPiServer: 8.1.0

**Comment by valdisiljuconoks** [comment]
Hi,

Interesting how duplicates got into the db. Might be some timing issues when running in cluster on multiple nodes.

I'll add check constraint for the resource key to prevent at least messing up with db.

**Comment by valdisiljuconoks** [comment]
package on the way to the feed..
