### ISSUE TITLE
Upgrading DbLocalizationProvider.EPiServer from 7.5.0 to 8.1.2

### ISSUE THREAD

**Issue by baskiattila** [valdisiljuconoks/localization-provider-opti#228]
Recently we tried to update DbLocalizationProvider.EPiServer package from 7.5.0 to 8.1.2, but on the next startup I got a SQL alter column error, because of the [IX_ResourceKey] index. After dropping it manually the application started and a new index with a different name was created. The new [ix_UniqueResourceKey] index has the same definition as the old one. I guess there was a change sometimes in the naming. Is it possible to drop both indexes before altering the [ResourceKey] column?

**Comment by valdisiljuconoks** [comment]
yeah, let me investigate more on this...

**Comment by baskiattila** [comment]
I retested with the 8.1.3 version, but the issue still there. I checked your commit and I think #9 change should happen before altering the column (#8 change).

![image](https://github.com/user-attachments/assets/36c19f0c-5555-41da-a84a-d51d4662ee91)

**Comment by valdisiljuconoks** [comment]
:rage-quit:
