### ISSUE TITLE
Multiple instances - values are stale

### ISSUE THREAD

**Issue by dariusz-wozniak** [valdisiljuconoks/localization-provider-opti#229]
In the multi-instance scenario, values on certain instances are pernamently wrong. Seems like values are not being invalidated. I don't want to run the "Clean Cache" button as it blew up the production last time.

Any suggestion how to solve that?

Using "DbLocalizationProvider.EPiServer" Version="8.1.4"

**Comment by valdisiljuconoks** [comment]
not being invalidated = after translation update?

**Comment by valdisiljuconoks** [comment]
how clean blew prod?

**Comment by dariusz-wozniak** [comment]
I was referring to that topic - https://github.com/valdisiljuconoks/localization-provider-opti/issues/220

But I cleared cache and the issue is gone, so I'm closing the ticket now.
