### ISSUE TITLE
Add localization provider after built-in providers

### ISSUE THREAD

**Issue by stefanolsen** [valdisiljuconoks/localization-provider-opti#230]
On a customer project, a Commerce solution, there was an issue where loading the editor UI issued thousands of SQL queries to get individual translation resources.

I found that ShellInitialization adds its EmbeddedXmlLocalizationProvider's to ProviderBasedLocalizationService, after the DbLocalizationProvider has added itself. So every time the UI needs an embedded resource, it will first attempt to load it from DbLocalizationProvider.

Would it be possible to add DbLocalizationProvider after EmbeddedXmlLocalizationProvider?

**Comment by valdisiljuconoks** [comment]
hey, this is the latest commerce, right?

**Comment by stefanolsen** [comment]
These are some of the package versions I am currently using:

- DbLocalizationProvider.EPiServer: 8.1.5
- EPiServer.CMS.UI: 12.31.1
- EPiServer.Commerce.UI: 14.24.0

**Comment by valdisiljuconoks** [comment]
btw, can you share you setup code? are you calling explicitly `services.AddEmbeddedLocalization<...>()` before adding `LocalizationProvider` ?

**Comment by stefanolsen** [comment]
Seems to work fine, if I add `.AddOptimizelyAdminUI()` to `services.AddDbLocalizationProviderAdminUI()`.

Thanks.
